part of 'chat_component.dart';

class ChatWindow extends StatelessWidget {
  const ChatWindow({super.key});

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;

    return AnimatedSize(
      duration: 400.milliseconds,
      child: Container(
        constraints: BoxConstraints(
          maxWidth: context.width * (context.isMobile ? 0.9 : 0.5),
        ),
        decoration: BoxDecoration(
          borderRadius: Sizes.borderRadiusRegular,
          color: colors.backgroundColor.withValues(alpha: 0.5),
          border: Border.all(
            color: colors.borderColor,
          ),
        ),
        child: ClipRRect(
          borderRadius: Sizes.borderRadiusRegular,
          clipBehavior: Clip.hardEdge,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                decoration: BoxDecoration(
                  color: colors.secondarySurface,
                ),
                padding: Sizes.paddingRegular,
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: Sizes.spacingSmall,
                  children: [
                    Text(
                      'AskYashas',
                      style: Styles.regularTextBold(),
                    ),
                    MouseRegion(
                      cursor: SystemMouseCursors.click,
                      child: GestureDetector(
                        onTap: ChatRepository.instance.clearChat,
                        child: Icon(
                          FontAwesomeIcons.solidTrashCan,
                          color: KnownColors.red400,
                          size: Sizes.iconSmall,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Expanded(
                child: Container(
                  padding: Sizes.paddingRegular,
                  child: ChatView(),
                ),
              ),
              Container(
                decoration: BoxDecoration(
                  color: colors.secondarySurface,
                ),
                padding: Sizes.paddingRegular,
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: Sizes.spacingRegular,
                  children: [
                    Icon(
                      FontAwesomeIcons.circleInfo,
                      color: colors.textColor.withValues(alpha: 0.7),
                      size: context.isMobile
                          ? Sizes.iconSmall
                          : Sizes.iconRegular,
                    ),
                    Flexible(
                      child: FittedBox(
                        fit: BoxFit.scaleDown,
                        child: Text(
                          'Disclaimer: Responses are generated by AI',
                          style: (context.isMobile
                                  ? Styles.smallText()
                                  : Styles.regularText())
                              .copyWith(
                                  color:
                                      colors.textColor.withValues(alpha: 0.7)),
                        ),
                      ),
                    )
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
